Update to use new Drupal Finder (Composer Runtime) API
drupal-composer/drupal-composer-project pull request #650
Opened 2024-05-13 12:56 UTC by jnoordsij

Drupal Finder has been revamped to use the Composer Runtime API, which makes it much simpler in how it operates. This PR updates the composer script handler to use this new Drupal Finder API. It also adds an additional panic exit in case the root cannot be found.

See also https://github.com/webflo/drupal-finder/releases/tag/1.3.0.

*Edit:* this requires some kind of additional work for new installations, given that the `Path::makeRelative` call seems to be failing on new installations, supposedly due to `getComposerRoot` returning `null` on fresh installations. I'm not sure yet on the fix that is required here (or maybe upstream?). A repeated `composer install` run seems to fix the issues.

2024-05-13 21:03 UTC, AlexSkrypnyk commented
@jnoordsij 
Thank you for contributing!

Confirming that this is a real issue and that we do need to provide support for the latest version of the `DrupalFider`.

Could you please update your PR to make it pass CI.

Thank you

2024-05-14 08:28 UTC, leymannx commented
Yeah if we can get that in with the CI succeed that would be really helpful. 👌🏻

2024-05-14 08:29 UTC, leymannx requested changes
Yeah if we can get that in with the CI succeed that would be really helpful. 👌🏻

2024-05-15 11:08 UTC, jnoordsij commented
I've quickly looked into this a bit further, but I'm very much unsure what's the possible cause of the CI failure. When trying to run this locally, I'm actually presented with an error at an earlier step:
```
[Symfony\Component\Filesystem\Exception\InvalidArgumentException]
  The path "/config/sync" cannot be made relative to ".../web", because they
  have different roots ("/" and "...").
```

However, after that, repeated composer runs and/or other commands run fine.

This makes it hard for me to debug what's exactly going on; so I'll just leave this open here for now for anyone interested in navigating this furter.

2024-06-07 08:48 UTC, leymannx commented
Fixed in https://github.com/drupal-composer/drupal-project/pull/673

2024-06-07 21:20 UTC, closed without merging